apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-resolver
  labels:
    app: url-resolver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-resolver
  template:
    metadata:
      labels:
        app: url-resolver
    spec:
      containers:
        - name: url-resolver
          image: urlresolver
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: url-resolver
spec:
  selector:
    app: url-resolver
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001